# Config for your Redshift host, database, and port
# Usernames and passwords are provided using environment variables

redshift_common: &redshift_common
  host: warehouse.pub.yourcompany.com
  database: warehouse
  port: '1234'
  statement_timeout: 1800000

production:
  <<: *redshift_common

staging:
  <<: *redshift_common

test:
  <<: *redshift_common

development:
  <<: *redshift_common
